### ISSUE TITLE
Not working in MacOS

### ISSUE THREAD

**Issue by AvikMallick** [epsilon573/AutomateOlympicCoding#1]

**Comment by epsilon573** [comment]
@AvikMallick pywinauto module is only available on windows.

**Comment by AvikMallick** [comment]
> @AvikMallick pywinauto module is only available on windows.

Then is there any other way to parse test cases automatically on mac?

**Comment by epsilon573** [comment]
I don't think so. Only possible way is to use selenium and manually automate clicks or manually paste link.
