### ISSUE TITLE
automate.py file is creating problem in line 17

### ISSUE THREAD

**Issue by Gurujyoti-polai** [epsilon573/AutomateOlympicCoding#2]
![Screenshot (962)](https://user-images.githubusercontent.com/79266786/158794334-4707ce6b-516b-4fda-8711-4baa03a446b5.png)
 
it is showing error like this when i try to run it using ctrl+b

**Comment by epsilon573** [comment]
Are you using chrome? And make sure it is running in the background.

**Comment by epsilon573** [comment]
Closing the issue due to inactivity.
